baseURL = 'https://stratospheric-dev.github.io'
languageCode = 'en-us'
title = 'Stratospheric - Spring Boot and AWS'
disableKinds = ["taxonomy", "taxonomyTerm"]

[markup.goldmark.renderer]
unsafe = true
